-- OBSOLETE / DO NOT IMPORT ON A FRESH INSTALL
-- The starter admin account is now included directly in database/schema.sql.
-- This file is kept only as historical reference from the v1 development pass.
